// <auto-generated />
using System;
using Lafise.Insurance.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lafise.Insurance.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InsuranceDbContext))]
    partial class InsuranceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("CertificateNumberSequence");

            modelBuilder.HasSequence<int>("PolicyNumberSequence");

            modelBuilder.Entity("Lafise.Insurance.Domain.Entities.Coverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Coverages_Name");

                    b.ToTable("Coverages", null, t =>
                        {
                            t.HasCheckConstraint("CK_Coverages_Rate", "[Rate] >= 0 AND [Rate] <= 100");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cubre el hurto total del vehículo asegurado.",
                            IsActive = true,
                            Name = "Robo",
                            Rate = 2.50m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Cubre daños propios por colisión o vuelco.",
                            IsActive = true,
                            Name = "Choque",
                            Rate = 3.25m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cubre daños a terceros en sus bienes y personas.",
                            IsActive = true,
                            Name = "Responsabilidad Civil",
                            Rate = 1.75m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cubre daños por incendio, rayo o explosión.",
                            IsActive = true,
                            Name = "Incendio",
                            Rate = 1.10m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Cubre la rotura de parabrisas y ventanas.",
                            IsActive = true,
                            Name = "Rotura de Cristales",
                            Rate = 0.60m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Cobertura descontinuada; se conserva sólo para pólizas históricas.",
                            IsActive = false,
                            Name = "Asistencia Vial",
                            Rate = 0.40m
                        });
                });

            modelBuilder.Entity("Lafise.Insurance.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("IdentificationNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Customers_IdentificationNumber");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maria.lopez@example.com",
                            IdentificationNumber = "001-120589-1002B",
                            IsActive = true,
                            Name = "Maria Fernanda Lopez"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carlos.mendoza@example.com",
                            IdentificationNumber = "281-030777-0005X",
                            IsActive = true,
                            Name = "Carlos Alberto Mendoza"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "compras@elnorte.example.com",
                            IdentificationNumber = "J0310000234567",
                            IsActive = true,
                            Name = "Distribuidora El Norte S.A."
                        });
                });

            modelBuilder.Entity("Lafise.Insurance.Domain.Entities.Policy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InsuredAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<decimal>("TotalPremium")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IssueDate")
                        .HasDatabaseName("IX_Policies_IssueDate");

                    b.HasIndex("PolicyNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Policies_PolicyNumber");

                    b.HasIndex("VehicleId");

                    b.HasIndex("CustomerId", "VehicleId")
                        .IsUnique()
                        .HasDatabaseName("UX_Policies_ActiveCustomerVehicle")
                        .HasFilter("[Status] = 1");

                    b.ToTable("Policies", null, t =>
                        {
                            t.HasCheckConstraint("CK_Policies_Dates", "[ExpirationDate] > [IssueDate]");

                            t.HasCheckConstraint("CK_Policies_InsuredAmount", "[InsuredAmount] > 0");

                            t.HasCheckConstraint("CK_Policies_TotalPremium", "[TotalPremium] >= 0");
                        });
                });

            modelBuilder.Entity("Lafise.Insurance.Domain.Entities.PolicyCoverage", b =>
                {
                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.Property<int>("CoverageId")
                        .HasColumnType("int");

                    b.Property<decimal>("AppliedRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PremiumAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PolicyId", "CoverageId");

                    b.HasIndex("CoverageId");

                    b.ToTable("PolicyCoverages", null, t =>
                        {
                            t.HasCheckConstraint("CK_PolicyCoverages_AppliedRate", "[AppliedRate] >= 0 AND [AppliedRate] <= 100");

                            t.HasCheckConstraint("CK_PolicyCoverages_PremiumAmount", "[PremiumAmount] >= 0");
                        });
                });

            modelBuilder.Entity("Lafise.Insurance.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("CommercialValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Plate")
                        .IsUnique()
                        .HasDatabaseName("UX_Vehicles_Plate");

                    b.ToTable("Vehicles", null, t =>
                        {
                            t.HasCheckConstraint("CK_Vehicles_CommercialValue", "[CommercialValue] > 0");

                            t.HasCheckConstraint("CK_Vehicles_Year", "[Year] BETWEEN 1900 AND 2200");
                        });
                });

            modelBuilder.Entity("Lafise.Insurance.Domain.Entities.Policy", b =>
                {
                    b.HasOne("Lafise.Insurance.Domain.Entities.Customer", "Customer")
                        .WithMany("Policies")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lafise.Insurance.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Policies")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Lafise.Insurance.Domain.Entities.PolicyCoverage", b =>
                {
                    b.HasOne("Lafise.Insurance.Domain.Entities.Coverage", "Coverage")
                        .WithMany("PolicyCoverages")
                        .HasForeignKey("CoverageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lafise.Insurance.Domain.Entities.Policy", "Policy")
                        .WithMany("Coverages")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coverage");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("Lafise.Insurance.Domain.Entities.Coverage", b =>
                {
                    b.Navigation("PolicyCoverages");
                });

            modelBuilder.Entity("Lafise.Insurance.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Policies");
                });

            modelBuilder.Entity("Lafise.Insurance.Domain.Entities.Policy", b =>
                {
                    b.Navigation("Coverages");
                });

            modelBuilder.Entity("Lafise.Insurance.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Policies");
                });
#pragma warning restore 612, 618
        }
    }
}
